language: go
dist: xenial
go:
  - "1.11.x"
matrix:
  include:
    - os: linux
      env:
        - PIP='sudo pip'
env:
  global:
    - XARGS="-screen 0 1024x768x24"
before_install:
  - source ./ci-scripts/install-$TRAVIS_OS_NAME.sh

install:
  - if [[ ! -d $GOPATH/src/github.com/skycoin/hardware-wallet-go ]]; then mkdir -p $GOPATH/src/github.com/skycoin; ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/skycoin/hardware-wallet-go; fi
  - go get github.com/vektra/mockery/.../
  - cd $GOPATH/src/github.com/skycoin/hardware-wallet-go
  - make mocks
  - make install-linters
  - make lint
  - go get -t ./...

before_script:
  # Install go dep
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  # Start Xvfb on osx
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
    ( sudo Xvfb :99 -ac ${XARGS}; echo "Xvfb ok" )&
    fi
  # Install hardware wallet for running tests against emulator
  - mkdir -p tmp/hardware-wallet
  - git clone --depth=1 --single-branch --branch develop https://github.com/skycoin/hardware-wallet.git tmp/hardware-wallet
  - git -C tmp/hardware-wallet submodule update --init
  # Install OS-specific test and build dependencies for hardware-wallet
  - ( cd ./tmp/hardware-wallet && sh "ci-scripts/install-${TRAVIS_OS_NAME}.sh" )
  # Define env vars for Linux builds
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
    ls -l /usr/local/bin/protoc;
    export PATH="/usr/local/bin:$(pwd)/tmp/hardware-wallet/protoc/bin:$PATH";
    fi
  # Include paths for brew packages e.g. SDL2
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    export SDL_INCLUDE="$(brew --prefix sdl2)/include/SDL2" ;
    fi
  - echo "PATH=$PATH";
  - echo "PIP=$PIP";

script:
  - make -C tmp/hardware-wallet clean
  - make -C tmp/hardware-wallet/tiny-firmware/protob install-protoc
  - make -C tmp/hardware-wallet/tiny-firmware/protob/nanopb/vendor/nanopb/generator/proto
  - make -C tmp/hardware-wallet emulator
  # On GNU/Linux wrap emulator in xvfb graphics context
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    xvfb-run --server-args="${XARGS}" make -C ./tmp/hardware-wallet run-emulator & true ;
    fi
  # On osx Xvfb started in before_script step
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
    make -C ./tmp/hardware-wallet run-emulator & true ;
    fi
  # Run self-tests
  - ps aux | grep emulator
  - make test_unit
  - make integration-test-emulator
  # Test that dependencies can be updated
  - make clean
  - make dep

after_script:
  - kill -s KILL $(pgrep emulator)

notifications:
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
